debug: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wenger-upms?characterEncoding=utf-8&useSSL=false
    username: root
    password: root